### PR TITLE
Build wheels for Apple Silicon Macs.

### PR DESCRIPTION
**Pull request by QuLogic**
Following: https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon

### CODE REVIEW

**Comment by QuLogic** [comment]
It looks like your GitHub Actions workflow was disabled for inactivity.

**Comment by QuLogic** [comment]
This fails on my repo because kiwi switched `master` to `main`, so I added another commit changing that.

**Comment by QuLogic** [comment]
Now building, except for the upload stage: https://github.com/QuLogic/kiwisolver-wheels/runs/2625725518

**Comment by MatthieuDartiailh** [comment]
I re-activated actions, and I will merge once the CIs comes back green.

**Comment by MatthieuDartiailh** [comment]
@matthew-brett since we are not using appveyor anymore, is there a way for you to remove it, I do not seem to be able to do it when logged through my Github account.

**Comment by MatthieuDartiailh** [comment]
@QuLogic could you also change the branch built by Travis ?

@matthew-brett do you have plan to migrate the travis.org to travis.com (we need travis for the exotic platforms), or should I somehow do it myself ?

**Comment by MatthieuDartiailh** [comment]
@matthew-brett any plan for Travis ? Also does anybody know how to get anaconda-client working ? the last version publish does not work and I cannot seem to get it to install cleanly from the github repo.

**Comment by matthew-brett** [comment]
Yes, latest pip install for anaconda client doesn't work.

Here's Biopython's setup - does it work for you?

https://github.com/biopython/biopython-wheels/blob/master/.travis.yml#L129

**Comment by MatthieuDartiailh** [comment]
I think I already tried (and got a nonsensical error about ruamel-yaml) but I will give it another spin.

**Comment by MatthieuDartiailh** [comment]
Also is there a way to diasble appveyor now that github action is used for windows ?

**Comment by MatthieuDartiailh** [comment]
Still the same weird error https://github.com/MacPython/kiwisolver-wheels/runs/2754277367?check_suite_focus=true

Ruamel-yaml is installed but distutils seems unhappy, I will try updating pip and installing wheel before see if it helps.

Anyway it should not try to upload from a PR so I fixed the conditional.

**Pull request merged**
